# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7ee94f2e1c43ab65c3353abd247e823a151a8090c1deafb36dbcd38c18f3670aca82f2eda0e52eada763d1069d93f2ff53235aca99a68de687c35da9e9ff5c8

test:
  secret_key_base: 2a37322f5901a5aaab05c26c041aaa7a0f5ba7af728f9aef8d7c17c31f71e7fd60a93119fafebbef289506f7f7d339a6d9484baba2b6d57703a786bcbd5f87bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
